/** @brief d&d 3.5e wild shape animals
 *  @author Sarah Rosanna Busch
 *  @date 30 Nov 2021
 */

const SA = {
    pounce: 'pounce: if it charges can make a full attack',
    improvedGrab: 'improved grab: if it hits, can grapple w/o provoking AoO',
    rake: 'rake: 2 claw attacks while grappling',
    constrict: 'constrict: on a successful grapple, squeeze (2d8+6)',
    ferocity: 'fights without penalty while disabled or dying'
}

export const ANIMALS = [
    {
        name: 'Half-Elf',
        size: 'medium',
        speed: 20,
        STR: 11,
        DEX: 12,
        CON: 12,
        naturalArmor: 9, //actually from armor (5) and shield (4)
        attack: "club (1d6) | silver dagger (1d4) [crits on 19] | sling (1d4)",
        fullAttack: "charge: 2x speed, +2 melee, -2 AC, +2 bull rush",
        specialAttacks: ['rhino hide armor: charge attack damage bonus (2d6)'],
        spaceReach: '5ft/5ft',
        skills: {},
        CR: 100, //so it's always on top
        link: 'https://www.d20srd.org/srd/races.htm#halfElves'
    }, {
        name: 'Eagle',
        size: 'small',
        speed: 10,
        flySpeed: 80,    
        STR: 10,
        DEX: 15,
        CON: 12,
        naturalArmor: 1+1, //plus size mod
        attack: "talons (1d4)",
        fullAttack: "2 talons (1d4), bite (1d4)",
        specialAttacks: [],
        spaceReach: '5ft/5ft',
        skills: {spot:8},
        CR: 0.5,
        link: 'http://www.d20srd.org/srd/monsters/eagle.htm'
    }, {
        name: 'Dire Bat',
        size: "large",
        speed: 20,
        flySpeed: 40, 
        STR: 17,
        DEX: 22,
        CON: 17,
        naturalArmor: 5,
        attack: "Bite (1d8+4)",
        fullAttack: "Bite (1d8+4)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {hide:4, listen:12, moveSilently:11, spot:8},
        CR: 2,
        link: 'http://www.d20srd.org/srd/monsters/direBat.htm'
    }, {
        name: 'Treant',
        size: "Huge Plant",
        speed: 30,
        STR: 29,
        DEX: 8,
        CON: 21,
        naturalArmor: 13,
        attack: "Slam (2d6+9)",
        fullAttack: "2 slams (2d6+9)",
        specialAttacks: ["Animate trees, double damage against objects, trample 2d6+13"],
        spaceReach: '15ft/15ft',
        skills: {diplomacy: 3, hide: -9, intimidate: 6, knowledgeNature: 6, listen: 8, senseMotive: 8,
        spot: 8, survival: 8, survivalInNature: 10},
        CR: 8,
        link: 'https://www.d20srd.org/srd/monsters/treant.htm'
    }, {
        name: 'Megaraptor',
        size: 'large',
        speed: 60,   
        STR: 21,
        DEX: 15,
        CON: 21,
        naturalArmor: 6-1,
        attack: "talons (2d6+5)",
        fullAttack: "talons (2d6+5), 2 foreclaws (1d4+2), bite (1d8+2)",
        specialAttacks: [SA.pounce],
        spaceReach: '10ft/5ft',
        skills: {hide:8, jump:8, listen:8, spot:8, survival:8, survivalInNature:8},
        CR: 6,
        link: "http://www.d20srd.org/srd/monsters/dinosaur.htm#megaraptor"
    }, {
        name: 'Dire Bear',
        size: 'large',
        speed: 40,   
        STR: 31,
        DEX: 13,
        CON: 19,
        naturalArmor: 7-1,
        attack: "claw (2d4+10)",
        fullAttack: "2 claws (2d4+10), bite (2d8+5)",
        specialAttacks: [SA.improvedGrab],
        spaceReach: '10ft/5ft',
        skills: {},
        CR: 7,
        link: 'http://www.d20srd.org/srd/monsters/direBear.htm'
    }, {
        name: 'Dire Tiger',
        size: 'large',
        speed: 40,   
        STR: 27,
        DEX: 15,
        CON: 17,
        naturalArmor: 6-1,
        attack: "claw (2d4+8)",
        fullAttack: "2 claws (2d4+8), bite (2d6+4)",
        specialAttacks: [SA.pounce, SA.improvedGrab, SA.rake + " (2d4+4)"],
        spaceReach: '10ft/5ft',
        skills: {hide:4, moveSilently:4, hideInTallGrass:8},
        CR: 8,
        link: 'http://www.d20srd.org/srd/monsters/direTiger.htm'
    }, {
        name: 'Giant Octopus',
        size: 'large',
        speed: 20, 
        swimSpeed: 30,  
        STR: 20,
        DEX: 15,
        CON: 13,
        naturalArmor: 7-1,
        attack: "tentacle (1d4+5)",
        fullAttack: "8 tentacles (1d4+5), bite (1d8+2)",
        specialAttacks: [SA.improvedGrab, SA.constrict],
        spaceReach: '10ft/10ft (20ft w/ tentacles)',
        skills: {hide:4, escapeArtist:10, swim:8},
        CR: 8,
        link: 'http://www.d20srd.org/srd/monsters/octopusGiant.htm'
    }, {
        name: 'Large Shark',
        size: "large",    
        swimSpeed: 60,
        STR: 17,
        DEX: 15,
        CON: 13,
        naturalArmor: 4,
        attack: "Bite (1d8+4)",
        fullAttack: "Bite (1d8+4)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {listen:8, spot:7, swim:11},
        CR: 2,
        link: 'http://www.d20srd.org/srd/monsters/shark.htm'
    }, {
        name: 'Manta Ray',
        size: "large",  
        swimSpeed: 30,
        STR: 15,
        DEX: 11,
        CON: 10,
        naturalArmor: 3,
        attack: "Ram (1d6+1)",
        fullAttack: "Ram (1d6+1)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {listen:7, spot:6, swim:10},
        CR: 1,
        link: 'http://www.d20srd.org/srd/monsters/mantaRay.htm'
    }, {
        name: 'Dire Ape',
        size: "large",
        speed: 30,
        climbSpeed: 15,  
        STR: 22,
        DEX: 15,
        CON: 14,
        naturalArmor: 4,
        attack: "Claw (1d6+6)",
        fullAttack: "2 claws (1d6+6) and bite (1d8+3)",
        specialAttacks: ["Rend 2d6+9"],
        spaceReach: '10ft/10ft',
        skills: {climb:14, listen:5, moveSilently:4, spot:6},
        CR: 3,
        link: 'http://www.d20srd.org/srd/monsters/direApe.htm'
    }, {
        name: 'Dire Boar',
        size: "large",
        speed: 40,
        STR: 27,
        DEX: 10,
        CON: 17,
        naturalArmor: 6,
        attack: "Gore (1d8+12)",
        fullAttack: "Gore (1d8+12)",
        specialAttacks: [SA.ferocity],
        spaceReach: '10ft/5ft',
        skills: {listen:8, spot:8},
        CR: 4,
        link: 'http://www.d20srd.org/srd/monsters/direBoar.htm'
    }, {
        name: 'Dire Lion',
        size: "large",
        speed: 40,
        STR: 25,
        DEX: 15,
        CON: 17,
        naturalArmor: 4,
        attack: "Claw (1d6+7)",
        fullAttack: "2 claws (1d6+7) and bite (1d8+3)",
        specialAttacks: [SA.improvedGrab, SA.pounce, SA.rake + " 1d6+3"],
        spaceReach: '10ft/5ft',
        skills: {hide:2, listen:7, moveSilently:5, spot:7},
        CR: 5,
        link: 'http://www.d20srd.org/srd/monsters/direLion.htm'
    }, {
        name: 'Dire Wolf',
        size: "large",
        speed: 50,
        STR: 25,
        DEX: 15,
        CON: 17,
        naturalArmor: 3,
        attack: "Bite (1d8+10)",
        fullAttack: "Bite (1d8+10)",
        specialAttacks: ["trip"],
        spaceReach: '10ft/5ft',
        skills: {hide:0, listen:7, moveSilently:4, spot: 7, survival: 2},
        CR: 3,
        link: 'http://www.d20srd.org/srd/monsters/direWolf.htm'
    }, {
        name: 'Dire Wolverine',
        size: "large",
        speed: 30,
        climbSpeed: 10,  
        STR: 22,
        DEX: 17,
        CON: 19,
        naturalArmor: 4,
        attack: "Claw (1d6+6)",
        fullAttack: "2 claws (1d6+6) and bite (1d8+3)",
        specialAttacks: ["rage"],
        spaceReach: '10ft/5ft',
        skills: {climb:14, listen:7, spot:7},
        CR: 4,
        link: 'http://www.d20srd.org/srd/monsters/direWolverine.htm'
    }, {
        name: 'Ape',
        size: 'large',
        speed: 30,
        climbSpeed: 30,  
        STR: 21,
        DEX: 15,
        CON: 14,
        naturalArmor: 3,
        attack: "claws (1d6+5)",
        fullAttack: "2 claws (1d6+5) and bite (1d6+2)",
        specialAttacks: [],
        spaceReach: '10ft/10ft',
        skills: {climb:14, listen:6, spot:6},
        CR: 2,
        link: 'http://www.d20srd.org/srd/monsters/ape.htm'
    }, {
        name: 'Brown Bear',
        size: "large",
        speed: 40,
        STR: 27,
        DEX: 13,
        CON: 19,
        naturalArmor: 5,
        attack: "Claw (1d8+8)",
        fullAttack: "2 claws (1d8+8) and bite (2d6+4)",
        specialAttacks: [SA.improvedGrab],
        spaceReach: '10ft/5ft',
        skills: {listen:4, spot:7, swim:12},
        CR: 4,
        link: 'http://www.d20srd.org/srd/monsters/bearBrown.htm'
    }, {
        name: 'Polar Bear',
        size: "large",
        speed: 40,   
        swimSpeed: 30,
        STR: 27,
        DEX: 13,
        CON: 19,
        naturalArmor: 5,
        attack: "Claw (1d8+8)",
        fullAttack: "2 claws (1d8+8) and bite (2d6+4)",
        specialAttacks: [SA.improvedGrab],
        spaceReach: '10ft/5ft',
        skills: {hide:-2, listen:5, spot:7, swim:16},
        CR: 4,
        link: 'http://www.d20srd.org/srd/monsters/bearPolar.htm'
    }, {
        name: 'Bison',
        size: "large",
        speed: 40,
        STR: 22,
        DEX: 10,
        CON: 16,
        naturalArmor: 4,
        attack: "Gore (1d8+9)",
        fullAttack: "Gore (1d8+9)",
        specialAttacks: ["Stampede"],
        spaceReach: '10ft/5ft',
        skills: {listen:7, spot:5},
        CR: 2,
        link: 'http://www.d20srd.org/srd/monsters/bison.htm'
    }, {
        name: 'Camel',
        size: "large",
        speed: 50,
        STR: 18,
        DEX: 16,
        CON: 14,
        naturalArmor: 1,
        attack: "Bite (1d4+2)",
        fullAttack: "Bite (1d4+2)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {listen:5, spot:5},
        CR: 1,
        link: 'http://www.d20srd.org/srd/monsters/camel.htm'
    }, {
        name: 'Lion',
        size: "large",
        speed: 40,
        STR: 21,
        DEX: 17,
        CON: 15,
        naturalArmor: 3,
        attack: "Claw (1d4+5)",
        fullAttack: "2 claws (1d4+5) and bite (1d8+2)",
        specialAttacks: [SA.pounce, SA.improvedGrab, SA.rake + " 1d4+2"],
        spaceReach: '10ft/5ft',
        skills: {balance:7, hide:3, listen:5, moveSilently:11, spot:5},
        CR: 3,
        link: 'http://www.d20srd.org/srd/monsters/lion.htm'
    }, {
        name: 'Rhinoceros',
        size: "large",
        speed: 30,
        STR: 26,
        DEX: 10,
        CON: 21,
        naturalArmor: 7,
        attack: "Gore (2d6+12)",
        fullAttack: "Gore (2d6+12)",
        specialAttacks: ["powerful charge: 4d6+24 charge damage"],
        spaceReach: '10ft/5ft',
        skills: {listen:14, spot:3},
        CR: 4,
        link: 'http://www.d20srd.org/srd/monsters/rhinoceros.htm'
    }, {
        name: 'Large Viper',
        size: "large",
        speed: 20,
        climbSpeed: 20,    
        swimSpeed: 20,
        STR: 10,
        DEX: 17,
        CON: 11,
        naturalArmor: 3,
        attack: "Bite (1d4 plus poison)",
        fullAttack: "Bite (1d4 plus poison)",
        specialAttacks: ["poison: 1d6 CON, FORT DC 11"],
        spaceReach: '10ft/5ft',
        skills: {balance:11, climb:11, hide:8, listen:5, spot:6, swim:8},
        CR: 2,
        link: 'http://www.d20srd.org/srd/monsters/snake.htm#viperSnake'
    }, {
        name: 'Tiger',
        size: "large",
        speed: 40,
        STR: 23,
        DEX: 15,
        CON: 17,
        naturalArmor: 3,
        attack: "Claw (1d8+6)",
        fullAttack: "2 claws (1d8+6) and bite (2d6+3)",
        specialAttacks: [SA.improvedGrab, SA.pounce, SA.rake + ' 1d8+3'],
        spaceReach: '10ft/5ft',
        skills: {balance:6, hide:3, listen:3, moveSilently:9, spot:3, swim:11},
        CR: 4,
        link: 'http://www.d20srd.org/srd/monsters/tiger.htm'
    }, {
        name: 'Mule',
        size: "large",
        speed: 30,
        STR: 16,
        DEX: 13,
        CON: 17,
        naturalArmor: 3,
        attack: "Hoof (1d4+3)",
        fullAttack: "2 hooves (1d4+3)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {listen:6, spot:6},
        CR: 1,
        link: 'http://www.d20srd.org/srd/monsters/mule.htm'
    }, {
        name: 'Heavy Horse',
        size: "large",
        speed: 50,
        STR: 16,
        DEX: 13,
        CON: 15,
        naturalArmor: 3,
        attack: "Hoof (1d6+1)",
        fullAttack: "2 hooves (1d6+1)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {listen:5, spot:4},
        CR: 1,
        link: 'http://www.d20srd.org/srd/monsters/horse.htm#horseHeavy'
    }, {
        name: 'Light Horse',
        size: "large",
        speed: 60,
        STR: 14,
        DEX: 13,
        CON: 15,
        naturalArmor: 3,
        attack: "Hoof (1d4+1)",
        fullAttack: "2 hooves (1d4+1)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {listen:4, spot:4},
        CR: 1,
        link: 'http://www.d20srd.org/srd/monsters/horse.htm#horseLight'
    }, {
        name: 'Heavy Warhorse',
        size: "large",
        speed: 50,
        STR: 18,
        DEX: 13,
        CON: 17,
        naturalArmor: 4,
        attack: "Hoof (1d6+4)",
        fullAttack: "2 hooves (1d6+4) and bite (1d4+2)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {listen:5, spot:4},
        CR: 2,
        link: 'http://www.d20srd.org/srd/monsters/horse.htm#warhorseHeavy'
    }, {
        name: 'Light Warhorse',
        size: "large",
        speed: 60,
        STR: 16,
        DEX: 13,
        CON: 17,
        naturalArmor: 4,
        attack: "Hoof (1d4+3)",
        fullAttack: "2 hooves (1d4+3) and bite (1d3+1)",
        specialAttacks: [],
        spaceReach: '10ft/5ft',
        skills: {listen:4, spot:4},
        CR: 1,
        link: 'http://www.d20srd.org/srd/monsters/horse.htm#warhorseLight'
    }, {
        name: 'Hawk',
        size: "tiny",
        speed: 10,
        flySpeed: 60,
        STR: 6,
        DEX: 17,
        CON: 10,
        naturalArmor: 2+2, //+ size
        attack: "talons (1d4-2)",
        fullAttack: "talons (1d4-2)",
        specialAttacks: [],
        spaceReach: '2.5ft/0ft',
        skills: {listen: 4, spot: 16},
        CR: '1/3',
        link: 'https://www.d20srd.org/srd/monsters/hawk.htm'
    }, {
        name: 'Viper Snake',
        size: "tiny",
        speed: 15,
        climbSpeed: 15,    
        swimSpeed: 15,
        STR: 4,
        DEX: 17,
        CON: 11,
        naturalArmor: 2+2,
        attack: "Bite (1 + 1d6 poison [FORT DC: 10])",
        fullAttack: "Bite (1 + poison )",
        specialAttacks: ['poison: 1d6 [FORT DC: 10]'],
        spaceReach: '2.5ft/0ft',
        skills: {balance: 11, climb: 11, hide: 15, listen: 6, spot: 6, swim: 5},
        CR: '1/3',
        link: 'https://www.d20srd.org/srd/monsters/snake.htm#viperSnake'
    }, {
        name: 'Owl',
        size: "tiny",
        speed: 10,
        flySpeed: 40,  
        STR: 4,
        DEX: 17,
        CON: 10,
        naturalArmor: 2+2,
        attack: "talons (1d4-3)",
        fullAttack: "talons (1d4-3)",
        specialAttacks: [],
        spaceReach: '2.5ft/0ft',
        skills: {listen: 14, moveSilently: 17, spot: 6},
        CR: 1/4,
        link: 'https://www.d20srd.org/srd/monsters/owl.htm'
    }, {
        name: 'Cat',
        size: "tiny",
        speed: 30,
        STR: 3,
        DEX: 15,
        CON: 10,
        naturalArmor: 2, //just size mod
        attack: "claw (1d2-4)",
        fullAttack: "claw (1d2-4), bite (1d4+3)",
        specialAttacks: [],
        spaceReach: '2.5ft/0ft',
        skills: {balance: 10, climb: 6, hide: 16, jump: 10, listen: 3, moveSilently: 8, spot: 3},
        CR: 1/4,
        link: 'https://www.d20srd.org/srd/monsters/cat.htm'
    }, {
        name: 'Weasel',
        size: "tiny",
        speed: 20,
        climbSpeed: 20,
        STR: 3,
        DEX: 15,
        CON: 10,
        naturalArmor: 2,
        attack: "bite (1d3-4)",
        fullAttack: "bite (1d3-4)",
        specialAttacks: ["attach"],
        spaceReach: '2.5ft/0ft',
        skills: {balance: 12, climb: 10, escapeArtist: 4, hide: 11, moveSilently: 8, spot: 3},
        CR: 1/4,
        link: 'https://www.d20srd.org/srd/monsters/weasel.htm'
    }, {
        name: 'Lizard',
        size: "tiny",
        speed: 20,
        climbSpeed: 20, 
        STR: 3,
        DEX: 15,
        CON: 10,
        naturalArmor: 2,
        attack: "bite (1d4-4)",
        fullAttack: "bite (1d4-4)",
        specialAttacks: [],
        spaceReach: '2.5ft/0ft',
        skills: {balance: 10, climb: 12, hide: 12, listen: 3, moveSilently: 4, spot: 3},
        CR: '1/6',
        link: 'https://www.d20srd.org/srd/monsters/lizard.htm'
    }, {
        name: 'Monkey',
        size: "tiny",
        speed: 30,
        climbSpeed: 30, 
        STR: 3,
        DEX: 15,
        CON: 10,
        naturalArmor: 2,
        attack: "bite (1d3-4)",
        fullAttack: "bite (1d3-4)",
        specialAttacks: [],
        spaceReach: '2.5ft/0ft',
        skills: {balance: 12, climb: 10, escapeArtist: 4, hide: 10, listen: 3, spot: 3},
        CR: '1/6',
        link: 'https://www.d20srd.org/srd/monsters/monkey.htm'
    }, {
        name: 'Raven',
        size: "tiny",
        speed: 10,
        flySpeed: 40, 
        STR: 1,
        DEX: 15,
        CON: 10,
        naturalArmor: 2,
        attack: "claws (1d2-5)",
        fullAttack: "claws (1d2-5)",
        specialAttacks: [],
        spaceReach: '2.5ft/0ft',
        skills: {listen: 5, spot: 7},
        CR: '1/6',
        link: 'https://www.d20srd.org/srd/monsters/raven.htm'
    }, {
        name: 'Rat',
        size: "tiny",
        speed: 15,
        climbSpeed: 15,    
        swimSpeed: 15,
        STR: 2,
        DEX: 15,
        CON: 10,
        naturalArmor: 2,
        attack: "bite (1d3-4)",
        fullAttack: "bite (1d3-4)",
        specialAttacks: [],
        spaceReach: '2.5ft/0ft',
        skills: {balance: 10, climb: 12, hide: 16, moveSilently: 10, swim: 10},
        CR: '1/8',
        link: 'https://www.d20srd.org/srd/monsters/rat.htm'
    }, {
        name: 'Rat Swarm',
        size: "tiny",
        speed: 15,
        climbSpeed: 15,  
        STR: 2,
        DEX: 15,
        CON: 10,
        naturalArmor: 2,
        attack: "swarm (1d6 + disease)",
        fullAttack: "swarm (1d6 + disease)",
        specialAttacks: ["disease, distraction"],
        spaceReach: '2.5ft/0ft',
        skills: {balance: 10, climb: 10, hide: 16, listen: 6, moveSilently:8, spot: 7, swim: 10},
        CR: 2,
        link: 'https://www.d20srd.org/srd/monsters/swarm.htm#ratSwarm'
    }, {
        name: 'Assassin Vine',
        size: "Large Plant",
        speed: 5,
        STR: 20,
        DEX: 10,
        CON: 16,
        naturalArmor: 6,
        attack: "Slam (1d6+7)",
        fullAttack: "Slam (1d6+7)",
        specialAttacks: ["Constrict 1d6+7, entangle, ", SA.improvedGrab, 
        "Blindsight 30 ft", "camouflage", "immunity to electricity",
        "plant traits", "resistance to cold 10 and fire 10"],
        spaceReach: '10ft/10ft (20ft with vine)',
        skills: {},
        CR: 3,
        link: 'https://www.d20srd.org/srd/monsters/assassinVine.htm'
    }, {
        name: 'Fungus, Shrieker',
        size: "Medium Plant",
        speed: 0,
        STR: 0,
        DEX: 0,
        CON: 13,
        naturalArmor: 3,
        attack: "",
        fullAttack: "",
        specialAttacks: ["Shriek", "Low-light vision, plant traits"],
        spaceReach: '5ft/0ft',
        skills: {},
        CR: 1,
        link: ''
    }, {
        name: 'Fungus, Violet',
        size: "Medium Plant",
        speed: 10,
        STR: 14,
        DEX: 8,
        CON: 16,
        naturalArmor: 4,
        attack: "Tentacle (1d6+2 plus poison)",
        fullAttack: "4 tentacles (1d6+2 plus poison)",
        specialAttacks: ["Poison", "Low-light vision, plant traits"],
        spaceReach: '5ft/10ft',
        skills: {},
        CR: 3,
        link: 'https://www.d20srd.org/srd/monsters/fungus.htm'
    }, {
        name: 'Phantom Fungus',
        size: "Medium Plant",
        speed: 20,
        STR: 14,
        DEX: 10,
        CON: 16,
        naturalArmor: 4,
        attack: "Bite (1d6+3)",
        fullAttack: "Bite (1d6+3)",
        specialAttacks: ["Low-light vision, plant traits, greater invisibility"],
        spaceReach: '5ft/5ft',
        skills: {listen: 4, moveSilently: 6, spot: 4},
        CR: 3,
        link: 'https://www.d20srd.org/srd/monsters/fungus.htm'
    }, {
        name: 'Shambling Mound',
        size: "Large Plant",
        speed: 20,   
        swimSpeed: 20,
        STR: 21,
        DEX: 10,
        CON: 17,
        naturalArmor: 11,
        attack: "Slam (2d6+5)",
        fullAttack: "2 slams (2d6+5)",
        specialAttacks: [SA.improvedGrab, "constrict 2d6+7",
        "Darkvision 60 ft., immunity to electricity, low-light vision, plant traits, resistance to fire 1"],
        spaceReach: '10ft/10ft',
        skills: {hide: 3, listen: 8, moveSilently: 8},
        CR: 6,
        link: 'https://www.d20srd.org/srd/monsters/shamblingMound.htm'
    }, {
        name: 'Tendriculos',
        size: "Huge Plant",
        speed: 20,
        STR: 28,
        DEX: 9,
        CON: 22,
        naturalArmor: 9,
        attack: "Bite (2d8+9)",
        fullAttack: "Bite (2d8+9), 2 tendrils (1d6+4)",
        specialAttacks: [SA.improvedGrab, "paralysis, swallow whole"],
        spaceReach: '15ft/15ft',
        skills: {hide: 0, listen: 1, moveSilently: 1, spot: 1},
        CR: 6,
        link: 'https://www.d20srd.org/srd/monsters/tendriculos.htm'
    }, {
        name: '',
        size: "",
        speed: 0,
        flySpeed: 0,    
        swimSpeed: 0,
        STR: 0,
        DEX: 0,
        CON: 0,
        naturalArmor: 0,
        attack: "",
        fullAttack: "",
        specialAttacks: [],
        spaceReach: '',
        skills: {},
        CR: 0,
        link: ''
    }
];